test:
	curl --header 'Access-Token: xxx' \
     --header 'Content-Type: application/json' \
     --data-binary '{"body":"WATER LEAK ALERT: LEVEL 149","title":"WATER LEAK ALERT","type":"note"}' \
     --request POST \
     https://api.pushbullet.com/v2/pushes
